### ISSUE TITLE
TypeError: '_Dispatch' object is not callable

### ISSUE THREAD

**Issue by jaye-li** [loonghao/photoshop-python-api#80]
**Describe the bug**
i run this example code：
`import photoshop.api as ps

app = ps.Application()
doc = app.documents.add()
new_doc = doc.artLayers.add()`

but ：
`Traceback (most recent call last):
  File "W:\00000-LJY\colorplan\jaye-p.py", line 4, in <module>
    doc = app.documents.add()
  File "C:\Users\LJY\AppData\Local\Programs\Python\Python39\lib\site-packages\photoshop\api\_documents.py", line 49, in add
    self.app.add(
TypeError: '_Dispatch' object is not callable`

may the 'add' methord cann't attachde to  the object 'doc'，how can i repair it?

**Desktop (please complete the following information):**
 - OS: [ Windows10]
 - Photoshop Version: [ Photoshop-2020]
 - Python Version: [python-3.9]

**Additional context**
thank you for your solution

**Comment by jaye-li** [comment]
@loonghao

**Comment by loonghao** [comment]
@jaye-li Same as this issue #44

I just want to confirm your photoshop is installed through the adobe installer or another way because photoshop python api needs to register the COM interface in the registration list to call photoshop, this error seems is the script did not find the corresponding object. You can try other examples to see if it can run normally.
